### ISSUE TITLE
How to run the example apps

### ISSUE THREAD

**Issue by epifanio** [LeonvanKouwen/elvis#1] opened 2020-10-14 11:16 UTC
HI, trying to run one of the 3 examples provided with the src code but I am getting errors. I am attaching the logs I got in the shell running the example - do you have any guidelines in how to run them? 

* live_time_series [log](https://gist.github.com/epifanio/89d7a6e3569c4367686574b037cdd4b6)
* plotly_based [log](https://gist.github.com/e0b50b2bcc79024d686a2773510565e1)
* science-dashboard [log](https://gist.github.com/f1f52718595bd1c26dd63d517399ce83)

**Comment by LeonvanKouwen** [comment] 2020-10-14 19:34
Hi @epifanio,

I cleaned up some small things so please pull the most recent version. I don't think that will fix your problem though. I just tested it with panel version 0.9.7 and it works. What version are you running? I suspect an older version; serving static assets is a pretty new feature (the error you get has to do with serving the static assets).

**Comment by LeonvanKouwen** [comment] 2020-10-16 14:13
Hi @epifanio  did you manage to run the examples?

**Comment by epifanio** [comment] 2020-10-18 12:42
@LeonvanKouwen , tested with up-to-date version of both elvis (pulled from git master branch) and panel - I got the same log:

```bash
(pdal) massimods@r740-5hdn2s2-ag-gcompute:/lustre/storeA/users/massimods/SW/SRC/elvis$ panel serve --allow-websocket-origin=xxx.xxx.xxx.xxx:5006 examples/live_time_series
2020-10-18 12:39:22,212 Starting Bokeh server version 2.1.1 (running on Tornado 6.0.4)
2020-10-18 12:39:22,226 User authentication hooks NOT provided (default user enabled)
2020-10-18 12:39:22,268 Bokeh app running at: http://localhost:5006/live_time_series
2020-10-18 12:39:22,268 Starting Bokeh server with process id: 236464
WARNING:param.reset: Setting non-parameter attribute value=False using a mechanism intended only for parameters
2020-10-18 12:39:49,560 Setting non-parameter attribute value=False using a mechanism intended only for parameters
2020-10-18 12:39:49,576 Starting Bokeh server version 2.1.1 (running on Tornado 6.0.4)
2020-10-18 12:39:49,576 User authentication hooks NOT provided (default user enabled)
Launching server at http://localhost:5050
2020-10-18 12:39:49,853 404 GET /assets/goldenlayout-base.css (xxx.xxx.xxx.xxx) 0.29ms
2020-10-18 12:39:49,861 404 GET /assets/panel-customizations-light.css (xxx.xxx.xxx.xxx) 0.25ms
2020-10-18 12:39:49,898 404 GET /assets/goldenlayout-elvis.css (xxx.xxx.xxx.xxx) 0.24ms
2020-10-18 12:39:49,903 404 GET /assets/panel-customizations.css (xxx.xxx.xxx.xxx) 0.23ms
2020-10-18 12:39:49,904 404 GET /assets/goldenlayout-elvis-light.css (xxx.xxx.xxx.xxx) 0.73ms
2020-10-18 12:39:49,970 404 GET /assets/js/jquery-1.11.1.min.js (xxx.xxx.xxx.xxx) 20.85ms
2020-10-18 12:39:50,064 404 GET /assets/js/goldenlayout.min.js (xxx.xxx.xxx.xxx) 0.22ms
2020-10-18 12:39:50,798 404 GET /assets/js/jquery-1.11.1.min.js (xxx.xxx.xxx.xxx) 0.21ms
2020-10-18 12:39:50,851 404 GET /assets/js/goldenlayout.min.js (xxx.xxx.xxx.xxx) 0.21ms
2020-10-18 12:39:50,986 WebSocket connection opened
2020-10-18 12:39:50,987 404 GET /favicon.ico (xxx.xxx.xxx.xxx) 0.67ms
2020-10-18 12:39:50,987 ServerConnection created
```

```python
^C(pdal) massimods@r740-5hdn2s2-ag-gcompute:/lustre/storeA/users/massimods/SW/SRC/elvis$ ipython
Python 3.8.6 | packaged by conda-forge | (default, Oct  7 2020, 19:08:05) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.18.1 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import panel

In [2]: panel.__version__
Out[2]: '0.9.7'
```

**Comment by epifanio** [comment] 2020-10-18 19:55
I tried running the example on a local machine (before was on a remote server) to check if the IP versus localhost was making any difference, but no luck.
I also tried to move around the assets directory (I tried adding a a copy in the root example directory, from where I run the command to start the app, and also a copy in the example directory itself ... but always same log. `404 GET /assets/..`

**Comment by nghenzi** [comment] 2020-10-18 20:18
Serving static assets works in 0.10 version, not yet released. Though you can install it with 

pip install git+https://github.com/holoviz/panel.git

and in this page you have the docs 

https://pyviz-dev.github.io/panel/reference/index.html

**Comment by epifanio** [comment] 2020-10-18 20:29
I somehow managed to run the examples from @jmosbacher  fork -  https://github.com/jmosbacher/elvis  - The examples were giving a similar error, but from the logs, I noticed it was looking for the `assets` directory into `/usr/local/lib/python3.8/dist-packages/assets`.

By manually copying the `assets` directory into `/usr/local/lib/python3.8/dist-packages` I got the examples in the fork running. I tried the same "hack" with the master branch but that didn't work.

The example in the fork was printing this log

```python
epinux@epidell:~/dev/elvis_fork$ panel serve --allow-websocket-origin=localhost:5006 examples/live_time_series
2020-10-18 22:12:38,241 Starting Bokeh server version 2.1.0 (running on Tornado 6.0.4)
2020-10-18 22:12:38,242 User authentication hooks NOT provided (default user enabled)
2020-10-18 22:12:38,244 Bokeh app running at: http://localhost:5006/live_time_series
2020-10-18 22:12:38,244 Starting Bokeh server with process id: 117104
WARNING:param.reset: Setting non-parameter attribute value=False using a mechanism intended only for parameters
2020-10-18 22:12:41,075 Setting non-parameter attribute value=False using a mechanism intended only for parameters
2020-10-18 22:12:41,504 Error running application handler <bokeh.application.handlers.directory.DirectoryHandler object at 0x7f5b3a6fa7f0>: [Errno 2] No such file or directory: '/usr/local/lib/python3.8/dist-packages/assets/goldenlayout-base.css'
File "goldenpanel.py", line 56, in load_css:
with open(path, "r") as f: Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/bokeh/application/handlers/code_runner.py", line 197, in run
    exec(self._code, module.__dict__)
  File "/home/epinux/dev/elvis_fork/examples/live_time_series/main.py", line 122, in <module>
    gpanel.serve(title="Time Series", show=False, port=5050)
  File "/usr/local/lib/python3.8/dist-packages/elvis/goldenpanel.py", line 77, in serve
    self._set_assets(self.css_dir, self.theme)
  File "/usr/local/lib/python3.8/dist-packages/elvis/goldenpanel.py", line 69, in _set_assets
    css = self.load_css(css_paths)
  File "/usr/local/lib/python3.8/dist-packages/elvis/goldenpanel.py", line 56, in load_css
    with open(path, "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/python3.8/dist-packages/assets/goldenlayout-base.css'
```

**Comment by epifanio** [comment] 2020-10-18 20:36
Hi @nghenzi, just saw your comment - after upgrading panel to git master - I got the following error:

```
panel serve --allow-websocket-origin=localhost:5006 examples/science-dashboard/
Traceback (most recent call last):
  File "/usr/local/bin/panel", line 5, in <module>
    from panel.command import main
  File "/usr/local/lib/python3.8/dist-packages/panel/__init__.py", line 5, in <module>
    from . import pane # noqa
  File "/usr/local/lib/python3.8/dist-packages/panel/pane/__init__.py", line 16, in <module>
    from .holoviews import HoloViews # noqa
  File "/usr/local/lib/python3.8/dist-packages/panel/pane/holoviews.py", line 20, in <module>
    from ..widgets import Player
  File "/usr/local/lib/python3.8/dist-packages/panel/widgets/__init__.py", line 10, in <module>
    from .file_selector import FileSelector  # noqa
  File "/usr/local/lib/python3.8/dist-packages/panel/widgets/file_selector.py", line 19, in <module>
    from .input import TextInput
  File "/usr/local/lib/python3.8/dist-packages/panel/widgets/input.py", line 16, in <module>
    from bokeh.models.widgets import (
ImportError: cannot import name 'NumericInput' from 'bokeh.models.widgets' (/usr/local/lib/python3.8/dist-packages/bokeh/models/widgets/__init__.py)
```
I will try to upgrade bokeh as well, to see if that fix the issue.

**Comment by nghenzi** [comment] 2020-10-18 20:36
As said previously, static assets are served in 0.10 version as documented here 
https://pyviz-dev.github.io/panel/user_guide/Deploy_and_Export.html 
in the static file hosting section

After installing the 0.10 version, you need to run a command like that 

panel serve some_script.py --static-dirs assets=./assets

I am not sure in the elvis package this works different. But in panel with this command it should work.

**Comment by nghenzi** [comment] 2020-10-18 20:37
I use python 3.7 because I saw some people with problems in python 3.8 in bokeh, and in panel.

**Comment by epifanio** [comment] 2020-10-18 21:25
I see, I opened an issue regarding the import error. I hope it makes sense: https://github.com/holoviz/panel/issues/1648

I already have all my environment in py3.8 (both bokeh and panel working fine) which problems did you or others found with py3.8?

I may try to study elvis's examples from the forked repo and keep an eye on the import issue in panel. 

Thanks a lot for the tips!

**Comment by epifanio** [comment] 2020-10-19 02:45
Upgrading bokeh fixed the issue with the import - the new version was masked by the old one - https://github.com/holoviz/panel/issues/1648

I then tried again with panel master, and I got:

```
epinux@epidell:~/dev/elvis$ panel serve --static-dirs assets=/home/epinux/dev/elvis/assets --allow-websocket-origin=localhost:5006 examples/science-dashboard/
2020-10-19 04:43:28,095 Starting Bokeh server version 2.2.2 (running on Tornado 6.0.4)
2020-10-19 04:43:28,096 User authentication hooks NOT provided (default user enabled)
2020-10-19 04:43:28,099 Bokeh app running at: http://localhost:5006/science-dashboard
2020-10-19 04:43:28,099 Starting Bokeh server with process id: 134373
WARNING:param.main: panel.callbacks module is deprecated and has been moved to panel.io.callbacks. Update your import as it will be removed in the next minor release.
2020-10-19 04:43:39,416 panel.callbacks module is deprecated and has been moved to panel.io.callbacks. Update your import as it will be removed in the next minor release.
2020-10-19 04:43:39,967 Error running application handler <bokeh.application.handlers.directory.DirectoryHandler object at 0x7ffb350adf40>: Cannot serve non-existent path /usr/local/lib/python3.8/dist-packages/assets
File "server.py", line 282, in get_static_routes:
raise ValueError("Cannot serve non-existent path %s" % path) Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/bokeh/application/handlers/code_runner.py", line 197, in run
    exec(self._code, module.__dict__)
  File "/home/epinux/dev/elvis/examples/science-dashboard/main.py", line 86, in <module>
    gpanel.serve(title="Science Dashboard", show=False, port=5051)
  File "/usr/local/lib/python3.8/dist-packages/elvis/goldenpanel.py", line 65, in serve
    return pn.serve(self.app, static_dirs={**assets_elvis, **static_dirs}, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/panel/io/server.py", line 247, in serve
    server = get_server(panels, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/panel/io/server.py", line 384, in get_server
    extra_patterns += get_static_routes(static_dirs)
  File "/usr/local/lib/python3.8/dist-packages/panel/io/server.py", line 282, in get_static_routes
    raise ValueError("Cannot serve non-existent path %s" % path)
ValueError: Cannot serve non-existent path /usr/local/lib/python3.8/dist-packages/assets
 
2020-10-19 04:43:40,181 WebSocket connection opened
2020-10-19 04:43:40,181 ServerConnection created
```

By manually adding the assets directory from `elvis` root dir into `/usr/local/lib/python3.8/dist-packages/assets` fixed it.

**Comment by epifanio** [comment] 2020-10-19 03:10
Ok got it running :) thanks a lot for the tips!

* installed `bokeh` and `panel` from git master (I had to manually remove old version of `bokeh`)
* then, running the example from the repository root, I had to modify the last line to point to the static assets directory:
```python
gpanel.serve(title="Science Dashboard", show=False, port=5051, static_dirs={'assets': './assets'})
```

**Comment by LeonvanKouwen** [comment] 2020-10-19 06:54
Hi @epifanio,
I am sorry about my earlier comment about panel 0.9.7. I checked again now I could reproduce your initial error. I think the first time the assets where still in the cache of the browser or something, making me think that static assets were already available in panel 0.9.7, but this is incorrect.

Thanks @nghenzi for chipping in!

Anyway, my main conda environment uses the developers install of panel ( [see instructions](https://panel.holoviz.org/developer_guide/index.html)), main branch. After that installation, and after installing holoviews and elvis itself with pip, it should just run out of the box, no need to add the assets folder manually.

So this makes me wonder why you had to do that... Did you use pip to install elvis? If not, maybe that explains it, and I should refactor to make that possible too somehow.

**Comment by epifanio** [comment] 2020-10-19 09:32
Hi @LeonvanKouwen , just to make sure I was using a clean environment I tried to put everything in a docker image and I tried to expose one of the examples on my server - it works!!!

I installed both panel and elvis from git with pip:

```dockerfile
RUN pip3 install git+https://github.com/holoviz/panel
RUN pip3 install git+https://github.com/LeonvanKouwen/elvis

```

I did not manually copy the assets directory - I only needed to edit the last line in the example:

```python
gpanel.serve(websocket_origin='xxx.xx.xx.xx:5050', 
            title="Time Series", 
            show=False, 
            port=5050, 
            static_dirs={'assets': './assets'})
```
And run it with:
```
panel serve --allow-websocket-origin=xxx.xx.xx.xx:5006 --allow-websocket-origin=xxx.xx.xx.xx:5050 examples/live_time_series/
```

When I hit the app URL with the browser `http://xxx.xx.xx.xx:5006/live_time_series` - this is the log in the shell output:

```
root@4bbc59bedbf4:~/notebooks/elvis# panel serve --allow-websocket-origin=xxx.xx.xx.xx:5006 --allow-websocket-origin=xxx.xx.xx.xx:5050 examples/live_time_series/2020-10-19 09:28:12,288 Starting Bokeh server version 2.2.2 (running on Tornado 6.0.4)
2020-10-19 09:28:12,289 User authentication hooks NOT provided (default user enabled)
2020-10-19 09:28:12,291 Bokeh app running at: http://localhost:5006/live_time_series
2020-10-19 09:28:12,291 Starting Bokeh server with process id: 277
WARNING:param.reset: Setting non-parameter attribute value=False using a mechanism intended only for parameters
2020-10-19 09:28:19,309 Setting non-parameter attribute value=False using a mechanism intended only for parameters
2020-10-19 09:28:19,338 Starting Bokeh server version 2.2.2 (running on Tornado 6.0.4)
2020-10-19 09:28:19,338 User authentication hooks NOT provided (default user enabled)
Launching server at http://localhost:5050
2020-10-19 09:28:19,449 404 GET /assets/goldenlayout-base.css (10.0.0.2) 1.05ms
2020-10-19 09:28:19,460 404 GET /assets/goldenlayout-elvis.css (10.0.0.2) 0.82ms
2020-10-19 09:28:19,513 404 GET /assets/panel-customizations.css (10.0.0.2) 0.83ms
2020-10-19 09:28:19,518 404 GET /assets/goldenlayout-elvis-light.css (10.0.0.2) 0.87ms
2020-10-19 09:28:19,529 404 GET /assets/panel-customizations-light.css (10.0.0.2) 0.70ms
2020-10-19 09:28:19,535 404 GET /assets/js/jquery-1.11.1.min.js (10.0.0.2) 0.85ms
2020-10-19 09:28:19,540 404 GET /assets/js/goldenlayout.min.js (10.0.0.2) 0.81ms
2020-10-19 09:28:19,795 WebSocket connection opened
2020-10-19 09:28:19,796 ServerConnection created
```

Which gives a blank page, but also starts the real application ... (I'm actually confused on what's happening here ...:-)

I then browse to `http://xxx.xx.xx.xx:5050/` 

```
2020-10-19 09:28:51,329 WebSocket connection closed: code=1001, reason=None
2020-10-19 09:28:51,700 WebSocket connection opened
2020-10-19 09:28:51,701 ServerConnection created
```
and I can successfully load and use the app :)
I am loving them! panel+elvis <3  Thank you so much for it!

**Comment by LeonvanKouwen** [comment] 2020-10-19 11:40
@epifanio, I am happy you got it working. I am closing the issue, but I have to say that the way you are running it right now is not the way it is supposed to run actually. I am surprised it even works :). 

In panel you can serve script directly using `pn.serve()`.  and run the script like `> python main.py`. Basically `gpanel.serve()` is wrapper around this method. 

Alternatively you can serve a directory using `pn.servable()` and run, like you did, `> panel examples\live_time_series`. Basically `gpanel.servable()` is a wrapper around that panel method, but this isn't well tested to be honest because I always use the first method. 

The way you are working now is kind of a mix between these two.  I would recommend using the first method because it is easier to use a debugger, but I'll test and possibly fix `gpanel.servable()` sometime later this week. The method you are using now might run into some kind of trouble sooner or later.

**Comment by LeonvanKouwen** [comment] 2020-10-19 11:41
Test, can I still comment?

**Closed as completed** 2020-10-19 11:41 UTC

**Comment by epifanio** [comment] 2020-10-19 13:59
@LeonvanKouwen,  thanks for taking the time to look into this!
I knew I was doing something weird ...  running `python3 examples/science-dashboard/main,py ` works as expected.
